# Rename this file to config.py and fill in your details
LASTFM_API_KEY = "PASTE_API_KEY_HERE"
LASTFM_API_SECRET = "PASTE_SHARED_SECRET_HERE"
LASTFM_USERNAME = "YOUR_LASTFM_USERNAME"
LASTFM_PASSWORD = "YOUR_LASTFM_PASSWORD"